### ISSUE TITLE
No Logs

### ISSUE THREAD

**Issue by BPM-NZ** [akpw/mktxp-stack#10]
Hi, love the project, MXTKP is working but no logs. In docker I can see balabit/syslog-ng:latest constantly restarting.

> exec /usr/sbin/syslog-ng: exec format error

Any help appreciated!

**Comment by akpw** [comment]
@BPM-NZ thanks for the good words. a quick question, do you use the [default configuration](https://github.com/akpw/mktxp-stack#default-stack), or the [fs-based](https://github.com/akpw/mktxp-stack#file-system-based-logs)? assuming the former / latter, what happens if you try the other one?

**Comment by BPM-NZ** [comment]
Thanks for the quick reply. First I tried the default which didn’t work and so then after I tried fs-based. Unfortunately both had the container restarting constantly.

**Comment by leewhat** [comment]
> Thanks for the quick reply. First I tried the default which didn’t work and so then after I tried fs-based. Unfortunately both had the container restarting constantly.

I suspect different platform, the image only for linux/amd64

**Comment by akpw** [comment]
@BPM-NZ have you resolved this?  if not, can you try updating the docker version to the latest
