### ISSUE TITLE
Monitoring data-loss

### ISSUE THREAD

**Issue by mzhafranrayhan** [akpw/mktxp-stack#12]
hello, I have an issues here, when I just turned on the stack, it ran smoothly and well, but in the next few moments, data-loss appeared, all dashboards could not provide visual data, but about 5-10 minutes later, visualization could is displayed again, do you have a solution? There are several Docker ports that I changed in Docker Compose to minimize port conflicts with other containers.

**Comment by akpw** [comment]
@mzhafranrayhan this one is a bit hard to trace without getting into specifics of your situation. 
conflicting ports could be a problem of course, which one do you need to change bcs of the conflicts?
