### ISSUE TITLE
Dont connect to router 

### ISSUE THREAD

**Issue by Men1steR** [akpw/mktxp-stack#13]
I can’t connect to the router, nothing is written in the log

``[Sample-Router]
    enabled = True         # turns metrics collection for this RouterOS device on / off

    hostname = 10.173.8.1    # RouterOS IP address
    port = 8728             # RouterOS IP Port

    username = support     # RouterOS user, needs to have 'read' and 'api' permissions
    password = test

    use_ssl = False                 # enables connection via API-SSL servis
    no_ssl_certificate = False      # enables API_SSL connect without router SSL certificate
    ssl_certificate_verify = False  # turns SSL certificate verification on / off

    installed_packages = True       # Installed packages
    dhcp = True                     # DHCP general metrics
    dhcp_lease = True               # DHCP lease metrics

    connections = True              # IP connections metrics
    connection_stats = False        # Open IP connections metrics

    pool = True                     # Pool metrics
    interface = True                # Interfaces traffic metrics

    firewall = True                 # IPv4 Firewall rules traffic metrics
    ipv6_firewall = False           # IPv6 Firewall rules traffic metrics
    ipv6_neighbor = False           # Reachable IPv6 Neighbors

    poe = True                      # POE metrics
    monitor = True                  # Interface monitor metrics
    netwatch = True                 # Netwatch metrics
    public_ip = True                # Public IP metrics
    route = True                    # Routes metrics
    wireless = True                 # WLAN general metrics
    wireless_clients = True         # WLAN clients metrics
    capsman = True                  # CAPsMAN general metrics
    capsman_clients = True          # CAPsMAN clients metrics

    user = True                     # Active Users metrics
    queue = True                    # Queues metrics

    remote_dhcp_entry = None        # An MKTXP entry for remote DHCP info resolution (capsman/wireless)

    use_comments_over_names = True  # when available, forces using comments over the interfaces names

    check_for_updates = False       # check for available ROS updates``

**Comment by Men1steR** [comment]
Exception occurred during processing of request from ('172.26.0.6', 49344)
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/socketserver.py", line 317, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/local/lib/python3.11/socketserver.py", line 348, in process_request
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.11/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.11/socketserver.py", line 755, in __init__
    self.handle()
  File "/usr/local/lib/python3.11/http/server.py", line 436, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.11/http/server.py", line 424, in handle_one_request

    method()
  File "/usr/local/lib/python3.11/site-packages/prometheus_client/exposition.py", line 270, in do_GET
    status, headers, output = _bake_output(registry, accept_header, accept_encoding_header, params, False)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/prometheus_client/exposition.py", line 105, in _bake_output
    output = encoder(registry)
             ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/prometheus_client/openmetrics/exposition.py", line 21, in generate_latest
    for metric in registry.collect():
  File "/usr/local/lib/python3.11/site-packages/prometheus_client/registry.py", line 97, in collect
    yield from collector.collect()
  File "/usr/local/lib/python3.11/site-packages/mktxp/flow/collector_handler.py", line 125, in collect
    yield from self.collect_sync()
  File "/usr/local/lib/python3.11/site-packages/mktxp/flow/collector_handler.py", line 44, in collect_sync
    yield from collect_func(router_entry)
  File "/usr/local/lib/python3.11/site-packages/mktxp/collector/connection_collector.py", line 34, in collect
    for connection_stat_record in connection_stats_records:
TypeError: 'NoneType' object is not iterable
----------------------------------------


I search log, how fixed it? Help pls

**Comment by Men1steR** [comment]
The problem was that after updating to ROS 7.12, for some reason the API port changed, although on another similar device it did not change after the updates

**Comment by theaustinayers** [comment]
> The problem was that after updating to ROS 7.12, for some reason the API port changed, although on another similar device it did not change after the updates

What did it change to? It still shows 8768 for me but I cannot get a connection either.

**Comment by akpw** [comment]
@theaustinayers you can change mktxp connection port in the main config as shown above, to match whatever is the current setting of you router
