### ISSUE TITLE
syslog-ng restaring

### ISSUE THREAD

**Issue by SerhiiZahuba** [akpw/mktxp-stack#14]
Hello. Help in solving the problem with the logs. After running docker compose, I see that one syslog-ng container is constantly restarting. In the logs, I noticed an error (on the screenshot) I don't understand where it wants to connect via TLS and also this is Operation not permitted' during 'pthread_create.

![image](https://github.com/akpw/mktxp-stack/assets/36307887/e954a449-0117-492e-8b74-981eb95c7a75)

**Comment by akpw** [comment]
@SerhiiZahuba can you try the [fs-based](https://github.com/akpw/mktxp-stack#file-system-based-logs) config, and see what happens there?

**Comment by SerhiiZahuba** [comment]
Yes, I run fs-based config . The problem was solved by updating docker to version 18, before that it was version 16. Thank you.

Thank you for this product - it is super great.
