### ISSUE TITLE
Problems with mktxp (under load)

### ISSUE THREAD

**Issue by SerhiiZahuba** [akpw/mktxp-stack#15]
After I add the third mikrotik to the config, the mktxp container does not work. It doesn't matter which mikrotik I will add the third one, but in the logs I see such a problem. Please help to solve it. thank you

`mktxp      | ----------------------------------------
mktxp      | Exception occurred during processing of request from ('192.168.110.117', 48900)
mktxp      | Traceback (most recent call last):
mktxp      |   File "/usr/local/lib/python3.12/socketserver.py", line 318, in _handle_request_noblock
mktxp      |     self.process_request(request, client_address)
mktxp      |   File "/usr/local/lib/python3.12/socketserver.py", line 349, in process_request
mktxp      |     self.finish_request(request, client_address)
mktxp      |   File "/usr/local/lib/python3.12/socketserver.py", line 362, in finish_request
mktxp      |     self.RequestHandlerClass(request, client_address, self)
mktxp      |   File "/usr/local/lib/python3.12/socketserver.py", line 761, in __init__
mktxp      |     self.handle()
mktxp      |   File "/usr/local/lib/python3.12/http/server.py", line 436, in handle
mktxp      |     self.handle_one_request()
mktxp      |   File "/usr/local/lib/python3.12/http/server.py", line 424, in handle_one_request
mktxp      |     method()
mktxp      |   File "/usr/local/lib/python3.12/site-packages/prometheus_client/exposition.py", line 329, in do_GET
mktxp      |     self.wfile.write(output)
mktxp      |   File "/usr/local/lib/python3.12/socketserver.py", line 840, in write
mktxp      |     self._sock.sendall(b)
mktxp      | BrokenPipeError: [Errno 32] Broken pipe
mktxp      | ----------------------------------------
`

**Comment by akpw** [comment]
looks like a prometheus config issue, discussed e.g. [here](https://github.com/akpw/mktxp/issues/29#issuecomment-1333434878)

**Comment by SerhiiZahuba** [comment]
So. I added 
scrape_interval: 2m
scrape_timeout: 2m
It helped a bit for 3 devices, but when I added 6 devices, loading the metrics page for prometheus was > 5 minutes. Perhaps you will have ideas on how to make the return of results faster?

**Comment by akpw** [comment]
Can you share the `MKXP metrics` part of the included dashboard? 

Also, have you tried [parallel router fetching](https://github.com/akpw/mktxp#mktxp-system-configuration)? This should help with things like scraping distributed routers over slow connections etc. You can then also use `max_scrape_duration` and  `total_max_scrape_duration` to further optimize the setup to your needs

**Comment by akpw** [comment]
> Can you share the MKXP metrics part of the included dashboard?

this one:

<img width="2840" alt="image" src="https://github.com/akpw/mktxp-stack/assets/5028474/9e8ca647-8537-448b-861f-23cb872a21db">

**Comment by SerhiiZahuba** [comment]
![image](https://github.com/akpw/mktxp-stack/assets/36307887/98e9075e-5849-499d-afb2-96f160b25982)


I only see this graph on some devices. Otherwise, the error is "No Data". I also see that according to those devices where everything shows a large indicator
IPConnectionCollector

I enabled parallel queries in the config, now prometheus works better.

One more thing, maybe it's important - now it doesn't show some graphics only for virtual (x86) mikrotik, maybe it coincided like that and maybe there are some restrictions with them?

**Comment by akpw** [comment]
"no data" probably means the scrapes for those virtual routers are cut due to default settings of the `max_scrape_duration` and `total_max_scrape_duration`. You can experiment with those, increasing to give more time for scrape processing on slower machines / connections. You can also disable more heavy collectors such as IPConnectionCollector, which seems to be taking a lot more time than usual (you can also check on that using the respective metrics as well)

**Comment by SerhiiZahuba** [comment]
I conducted several experiments, unfortunately, the information is loaded for quite a long time.
For example, I took three routers in the configuration.
The configuration is below.

![image](https://github.com/akpw/mktxp-stack/assets/36307887/03b46108-2e72-4de7-837b-581b5eb39ed1)

![image](https://github.com/akpw/mktxp-stack/assets/36307887/8ba3d643-635e-4749-a3b1-c1accf340c12)




Loading the page takes more than 2 minutes.
![image](https://github.com/akpw/mktxp-stack/assets/36307887/79a93749-28d3-403e-ae9c-20673309acf3)

**Comment by akpw** [comment]
can you run some commands from the mktxp container, to print out some CLI metrics (dhcp, wifi, capsman, etc) and see how long it takes for individual routers?

```
docker exec -ti mktxp sh
mktxp print -en MKTXP -h
```
e.g
```
mktxp print -en MKTXP -d
mktxp print -en MKTXP -w
mktxp print -en MKTXP -cc
mktxp print -en MKTXP -cn
...
```

**Comment by SerhiiZahuba** [comment]
mktxp print -en MKTXP -cn = **35 seconds**
mktxp print -en MKTXP -d = **0.5 seconds**
mktxp print -en MKTXP -w =  **0.5 seconds**
mktxp print -en MKTXP -cc =  **0.5 seconds**


as a temporary solution, I made a separate container in docker for each router

**Comment by akpw** [comment]
apart from the connection stats that do seem to take long, the rest seems OK and things should work fine with a single container & parallel execution. One more thing, can you experiment with `max worker _threads` giving it higher / lower numbers to see if there is an impact? also. make sure your docker is latest version

**Comment by SerhiiZahuba** [comment]
Sorry for the late reply. Yes, I tried to experiment with max worker _threads setting 3-5, but it did not help. Now I have divided each router into its own docker container - collecting statistics now from 4 seconds to 35 seconds maximum.

**Comment by akpw** [comment]
Parallel execution should work OK (it definitely does for lots of people), I'd say there is some misconfiguration for your specific environment. 

according to those values in your config:
>max scrape duration = 25 

any individual router scrape longer than 25sec will be cut off

>total _max_scrape duration = 35

`all` of the parallel scrapes (including those still in the queue) will be cut off if the  overall execution time takes longer than this value

was this set as intended for your use case? with some of your router scrapes taking longer time, this might be related

**Comment by aryapramudika** [comment]
Any suggestion to fix this issue? when i add 1 router is fine but for 4 router it showing error same like this

**Comment by aryapramudika** [comment]
After i configure separate containers per-router, the broken pipe is done.

But in ROS v7. i have new issue.

Hit timeout

![image](https://github.com/akpw/mktxp-stack/assets/61450033/11607419-d6a1-4b27-9da1-2c71474b5e85)


My Config:

![image](https://github.com/akpw/mktxp-stack/assets/61450033/c951166d-d169-48b0-a217-d8f49db51f36)

**Comment by akpw** [comment]
the message indicates that the router scrapes takes longer time that `max_scrape_duration`. This is a mktxp parallel fetch feature to drop off scrapes that takes longer time over slow network connections, you can simple increase the related setting to extend that limit.

also as mentioned before, with right configuration for your environment there should be no need for separate containers per router. but if you do this, probably does not make much sense to use parallel fetch either.
