### ISSUE TITLE
Mount error: prometheus.yml is a directory

### ISSUE THREAD

**Issue by Taverius** [akpw/mktxp-stack#17]
Was attempting to bring up the main stack (via Portainer).

`Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/data/compose/1/prometheus/prometheus.yml" to rootfs at "/etc/prometheus/prometheus.yml": mount /data/compose/1/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type`

I checked and indeed:
`root@server:/data/compose/1/prometheus# ls -l`
`total 4`
`drwxr-xr-x 2 root root 4096 Feb 10 01:40 prometheus.yml`

Its a directory.

**Comment by akpw** [comment]
well, apparently it's not. looks strange, have you found what was the problem?
