### ISSUE TITLE
Latest Loki (3.x) not starting with included config.

### ISSUE THREAD

**Issue by gallogabor** [akpw/mktxp-stack#19]
With current `grafana/loki:latest` (as of 2024-04-09), the Loki container not starting up because of schema and config changes needed for Loki 3.x series. Multiple errors showing up in container logs and server not starting.

To solve this, I'm using the latest Loki 2.x as `grafana/loki:2.9.6` instead of `:latest`, and this works as expected.

Please note this fact in the readme of this project for futore reference, maybe change/include Loki config for 3.x versions. I'm never used Loki before, so I can't provide a working config for it, sorry.

**Comment by akpw** [comment]
@gallogabor OK switched to 3.x as the default config, can you try it now?

**Comment by davidian-sk** [comment]
@akpw Works (at least) for me, thanks for the prompt update. Thumbs Up!
