### ISSUE TITLE
More than 4 devices error

### ISSUE THREAD

**Issue by Gero6700** [akpw/mktxp-stack#22]
I have this file and when I add more than 4 devices it does not synchronize nor does grafana or loki work. how do I fix it or what is wrong?

**Comment by akpw** [comment]
any specifics regarding your configs / environments? 
also, have you tried looking at some logs (e.g. `docker logs mktxp`) & checking the [mktxp forums](https://github.com/akpw/mktxp/issues?q=is%3Aissue+is%3Aclosed) for how to resolve configuration issues?

**Comment by Gero6700** [comment]
Nothing appears in the mktxp logs, I attach the configuration file but I have only modified the user and password, as you can see.
If I disable one of them it works, otherwise it doesn't work. I can only have 4 simultaneously.

--------------------------------------------------------------------------------------------------------------------------

## Copyright (c) 2020 Arseniy Kuznetsov
##
## This program is free software; you can redistribute it and/or
## modify it under the terms of the GNU General Public License
## as published by the Free Software Foundation; either version 2
## of the License, or (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.


[W-1]
    # for specific configuration on the router level, change here the defaults values from below
    hostname = 192.168.254.101

[W-2]
    # for specific configuration on the router level, change here the defaults values from below
    hostname = 192.168.254.102

[W-2]
    # for specific configuration on the router level, change here the defaults values from below
    hostname = 192.168.254.104

[W-3]
    # for specific configuration on the router level, change here the defaults values from below
    hostname = 192.168.254.105

[W-4]
    # for specific configuration on the router level, change here the defaults values from below
    hostname = 192.168.254.106



[default]
    # this affects configuration of all routers, unless overloaded on their specific levels

    enabled = True          # turns metrics collection for this RouterOS device on / off
    hostname = localhost    # RouterOS IP address
    port = 8728             # RouterOS IP Port

    username = mktxp_monitoring     # RouterOS user, needs to have 'read' and 'api' permissions
    password = 1234

    use_ssl = False                 # enables connection via API-SSL servis
    no_ssl_certificate = False      # enables API_SSL connect without router SSL certificate
    ssl_certificate_verify = False  # turns SSL certificate verification on / off
    plaintext_login = True          # for legacy RouterOS versions below 6.43 use False

    installed_packages = True       # Installed packages
    dhcp = True                     # DHCP general metrics
    dhcp_lease = True               # DHCP lease metrics

    connections = True              # IP connections metrics
    connection_stats = False        # Open IP connections metrics

    interface = True                # Interfaces traffic metrics

    route = True                    # IPv4 Routes metrics
    pool = True                     # IPv4 Pool metrics
    firewall = True                 # IPv4 Firewall rules traffic metrics
    neighbor = True                 # IPv4 Reachable Neighbors

    ipv6_route = False              # IPv6 Routes metrics
    ipv6_pool = False               # IPv6 Pool metrics
    ipv6_firewall = False           # IPv6 Firewall rules traffic metrics
    ipv6_neighbor = False           # IPv6 Reachable Neighbors

    poe = True                      # POE metrics
    monitor = True                  # Interface monitor metrics
    netwatch = True                 # Netwatch metrics
    public_ip = True                # Public IP metrics
    wireless = True                 # WLAN general metrics
    wireless_clients = True         # WLAN clients metrics
    capsman = True                  # CAPsMAN general metrics
    capsman_clients = True          # CAPsMAN clients metrics

    kid_control_assigned = False    # Allow Kid Control metrics for connected devices with assigned users
    kid_control_dynamic = False     # Allow Kid Control metrics for all connected devices, including those without assigned user

    user = True                     # Active Users metrics
    queue = True                    # Queues metrics

    bgp = False                     # BGP sessions metrics

    remote_dhcp_entry = None        # An MKTXP entry to provide for remote DHCP info / resolution
    remote_capsman_entry = None     # An MKTXP entry to provide for remote capsman info

    use_comments_over_names = True  # when available, forces using comments over the interfaces names

    check_for_updates = False       # check for available ROS updates

**Comment by akpw** [comment]
...and what happens if you fix the double [W-2] entry in your config? 

Most likely the config parser just fails on that one, you can check on that via getting into your docker container and running mktxp there from cmd:
```
docker exec -ti mktxp sh
mktxp print -en W-2 -h
```

**Comment by Gero6700** [comment]
Sorry, the configuration file is this one, it's just that since I changed the names I missed that one.

`[W-1]
    # for specific configuration on the router level, change here the defaults values from below
    hostname = 192.168.254.101

[W-2]
    # for specific configuration on the router level, change here the defaults values from below
    hostname = 192.168.254.102

[WCORP-3]
    # for specific configuration on the router level, change here the defaults values from below
    hostname = 192.168.254.104

#[W-4]
    # for specific configuration on the router level, change here the defaults values from below
#    hostname = 192.168.254.105

[WCORP-5]
    # for specific configuration on the router level, change here the defaults values from below
    hostname = 192.168.254.106



[default]
    # this affects configuration of all routers, unless overloaded on their specific levels

    enabled = True          # turns metrics collection for this RouterOS device on / off
    hostname = localhost    # RouterOS IP address
    port = 8728             # RouterOS IP Port

    username = mktxp_monitoring     # RouterOS user, needs to have 'read' and 'api' permissions
    password = @password

    use_ssl = False                 # enables connection via API-SSL servis
    no_ssl_certificate = False      # enables API_SSL connect without router SSL certificate
    ssl_certificate_verify = False  # turns SSL certificate verification on / off
    plaintext_login = True          # for legacy RouterOS versions below 6.43 use False

    installed_packages = True       # Installed packages
    dhcp = True                     # DHCP general metrics
    dhcp_lease = True               # DHCP lease metrics

    connections = True              # IP connections metrics
    connection_stats = False        # Open IP connections metrics

    interface = True                # Interfaces traffic metrics

    route = True                    # IPv4 Routes metrics
    pool = True                     # IPv4 Pool metrics
    firewall = True                 # IPv4 Firewall rules traffic metrics
    neighbor = True                 # IPv4 Reachable Neighbors

    ipv6_route = False              # IPv6 Routes metrics
    ipv6_pool = False               # IPv6 Pool metrics
    ipv6_firewall = False           # IPv6 Firewall rules traffic metrics
    ipv6_neighbor = False           # IPv6 Reachable Neighbors

    poe = True                      # POE metrics
    monitor = True                  # Interface monitor metrics
    netwatch = True                 # Netwatch metrics
    public_ip = True                # Public IP metrics
    wireless = True                 # WLAN general metrics
    wireless_clients = True         # WLAN clients metrics
    capsman = True                  # CAPsMAN general metrics
    capsman_clients = True          # CAPsMAN clients metrics

    kid_control_assigned = False    # Allow Kid Control metrics for connected devices with assigned users
    kid_control_dynamic = False     # Allow Kid Control metrics for all connected devices, including those without assigned user

    user = True                     # Active Users metrics
    queue = True                    # Queues metrics

    bgp = False                     # BGP sessions metrics

    remote_dhcp_entry = None        # An MKTXP entry to provide for remote DHCP info / resolution
    remote_capsman_entry = None     # An MKTXP entry to provide for remote capsman info

    use_comments_over_names = True  # when available, forces using comments over the interfaces names

    check_for_updates = False       # check for available ROS updates`

**Comment by Gero6700** [comment]
I have tried what you have told me and look, data in theory has and pulls out.

![imagen](https://github.com/akpw/mktxp-stack/assets/72683618/546455b7-090b-4be8-a53f-e3360c440028)

**Comment by akpw** [comment]
OK, can you switch to verbose logging and check the docker mktxp logs again?
you can also switch to parallel router fetching, to see if it changes anything:
```
$ mktxp edit -i -ed nano
     ...
     verbose_mode = True
     fetch_routers_in_parallel = True
$ docker restart mktxp
```

Also check on hitting the prometheus python client config issue as discussed [here](https://github.com/akpw/mktxp/issues/29#issuecomment-1333434878)

**Comment by Gero6700** [comment]
That worked for me, thank you!!!!
