### ISSUE TITLE
Update stack without data loss

### ISSUE THREAD

**Issue by ventra007** [akpw/mktxp-stack#24]
Hi,

How do we go about updating the containers to the latest version without losing historical data and custom grafana dashboards?

The commands I ran:
`docker compose -f docker-compose-mktxp-stack.yml down`
`docker compose -f docker-compose-mktxp-stack.yml pull`
`docker compose -f docker-compose-mktxp-stack.yml up -d`

All the containers are up to date, but my custom grafana users / dashboards are lost, and historical data is missing from mktxp.

**Comment by akpw** [comment]
@ventra007 at this point, only the fs-based logs are stored in a mounted local host volume, thus being permanent and not container-ephemeral. Switching prometheus / grafana containers to use mounted volumes will assure data persistency for those as well, when I get to it at some point.

**Comment by ventra007** [comment]
Hi,

Thanks for the reply, I managed to get what i needed by changing the `docker-compose-mktxp-stack.yml` file:

grafana:

volumes:
    - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
    - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
    - /opt/mktxp/grafana/data/dashboards:/var/lib/grafana/dashboards
    - /opt/mktxp/grafana/data:/var/lib/grafana

prometheus:

volumes:
    - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    - /opt/mktxp/prometheus/data:/prometheus

Obviously this will only work if the folders are created beforehand. 
`chmod 755` the created folders
`docker compose -f docker-compose-mktxp-stack.yml down`
`docker compose -f docker-compose-mktxp-stack.yml up -d`
And all data should copy across and stay persistent.

**Comment by akpw** [comment]
@ventra007 fyi, I added the grafana / prometheus mounted volumes as mentioned above so the data there should be persistent out-of-the-box & without extra setup required.

**Comment by akpw** [comment]
closing for now, feel free to reopen if any related problem found
