### ISSUE TITLE
Log Entry Duplication

### ISSUE THREAD

**Issue by ardichoke** [akpw/mktxp-stack#27]
I've been using your instructions for setting up logging to Loki as a rough template for integrating Mikrotik log shipping into an existing Loki server that I have. It looks like your instructions result in duplicating messages though (for instance, I set up logging rules to ship info and wireless log entries, which results in anything that is `info,wireless` being shipped twice). Am I missing something in your setup where this would be deduplicated, or is this the intended behavior?

**Comment by akpw** [comment]
well, this project obviously does not control how mikrotik devices send logs to remote servers... 
Regarding the instructions, I guess setting up a device not to ship either `info` or `wireless` logs would resolve the duplicates for the case you describe, at the cost of missing the ones which are not in both.
