### ISSUE TITLE
How to configure Syslog?

### ISSUE THREAD

**Issue by ksteink** [akpw/mktxp-stack#3]
I tried to follow your guide but is not clear what configuration needs to be done to get syslog to work.  What I am looking is the following:

- Log multiple Mikrotik Routers / Devices via Syslog.
- On the server I want that each device gets its own log file (i.e., Mikrotik1.log for Mikrotik Router1, Mikrotik2.log for Mikrotik Router 2 and so on.)
- Aside of the core functionality of the mktxp-stack I want to logrotate the logs to keep a retention of XX days (i.e., 90 days).
- I don't see in syslog configuration file an option where to store the logs.  I want to use /var/log/network subfolder.

If I try to modify the syslog configuration file in the container the container gets restarting all the time.  

I appreciate your guidance as I am new on this and I am having a hard time to follow.  You installation guide focuses on what I need to configure on the Mikrotik router to send the logs but is very vague on what I need to do on the container side.

Pls advise.

Thanks!

**Comment by akpw** [comment]
@ksteink I added the requested functionality, feel free to try out via:
```
docker-compose -f docker-compose-mktxp-stack-fs.yml up -d
```

described it in the docs as well, basically this configuration tells syslog to log into per-device files and then have promtail take it from there. you can change the default log folder in [docker-compose-mktxp-stack-fs.yml](https://github.com/akpw/mktxp-stack/blob/main/docker-compose-mktxp-stack-fs.yml), and set up log rotation as needed
