### ISSUE TITLE
mktxp is down but Loki is working

### ISSUE THREAD

**Issue by rackifiaustin** [akpw/mktxp-stack#4]
I am running a Ubuntu 22.04 server and I have this issue:

Get "http://mktxp:49090/metrics": dial tcp: lookup mktxp on 127.0.0.11:53: server misbehaving

This is under the Prometheus targets.

Not quite sure what I need to do to fix this.

Prometheus shows the mktxp target is down but when I go to :49009 I see - 

# HELP python_gc_objects_collected_total Objects collected during gc
# TYPE python_gc_objects_collected_total counter
python_gc_objects_collected_total{generation="0"} 3983.0
python_gc_objects_collected_total{generation="1"} 400.0
python_gc_objects_collected_total{generation="2"} 0.0
# HELP python_gc_objects_uncollectable_total Uncollectable object found during GC
# TYPE python_gc_objects_uncollectable_total counter
python_gc_objects_uncollectable_total{generation="0"} 0.0
python_gc_objects_uncollectable_total{generation="1"} 0.0
python_gc_objects_uncollectable_total{generation="2"} 0.0
# HELP python_gc_collections_total Number of times this generation was collected
# TYPE python_gc_collections_total counter
python_gc_collections_total{generation="0"} 86.0
python_gc_collections_total{generation="1"} 7.0
python_gc_collections_total{generation="2"} 0.0
# HELP python_info Python platform information
# TYPE python_info gauge
python_info{implementation="CPython",major="3",minor="11",patchlevel="1",version="3.11.1"} 1.0
# HELP process_virtual_memory_bytes Virtual memory size in bytes.
# TYPE process_virtual_memory_bytes gauge
process_virtual_memory_bytes 4.1906176e+07
# HELP process_resident_memory_bytes Resident memory size in bytes.
# TYPE process_resident_memory_bytes gauge
process_resident_memory_bytes 3.4025472e+07
# HELP process_start_time_seconds Start time of the process since unix epoch in seconds.
# TYPE process_start_time_seconds gauge
process_start_time_seconds 1.67193185371e+09
# HELP process_cpu_seconds_total Total user and system CPU time spent in seconds.
# TYPE process_cpu_seconds_total counter
process_cpu_seconds_total 0.55
# HELP process_open_fds Number of open file descriptors.
# TYPE process_open_fds gauge
process_open_fds 92.0
# HELP process_max_fds Maximum number of open file descriptors.
# TYPE process_max_fds gauge
process_max_fds 1.048576e+06
# HELP mktxp_internet_bandwidth Internet bandwidth in bits per second
# TYPE mktxp_internet_bandwidth gauge
mktxp_internet_bandwidth{direction="download"} 3.4119372042314416e+08
mktxp_internet_bandwidth{direction="upload"} 4.3886573060725015e+08
# HELP mktxp_internet_latency Internet latency in milliseconds
# TYPE mktxp_internet_latency gauge
mktxp_internet_latency 41.764

**Comment by rackifiaustin** [comment]
Update:
I edited the docker-compose-mktxp-stack.yml file and changed the mktxp volumes to:
./mktxp/:/root/mktxp-stack/mktxp
Which is where the mktxp.conf is 

This has now show mktxp UP in Prometheus but still nothing on the Grafana board.

**Comment by akpw** [comment]
@rackifiaustin upon a regular [mktxp-stack install](https://github.com/akpw/mktxp-stack#install--getting-started), mktxp should be installed & running under the mktxp user, not root. 
you should be able to check via the following:
```
docker exec -ti mktxp sh 
whoami
mktxp edit
```

**Comment by rackifiaustin** [comment]
When running "docker exec -ti mktxp sh" as "mktxp" I get:

[
mktxp@noc:~/mktxp-stack$ docker exec -ti mktxp sh
Got permission denied while trying to connect to the Docker daemon socket at uni                                                x:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/container                                                s/mktxp/json": dial unix /var/run/docker.sock: connect: permission denied
]

I assigned sudo permission to mktxp and did "sudo apt install docker-compose" but receive this error as mktxp is not able to connect to the Docker engine

**Comment by akpw** [comment]
@rackifiaustin no need to give mktxp user sudo permission, nor run docker exec / compose under it. 
that user is created by docker according to the instruction from [mktxp docker file](https://github.com/akpw/mktxp/blob/main/Dockerfile), and then automatically used for running the app within the container. 

so you should run `docker exec -ti mktxp sh` as your regular user instead, which would take you to the running container where you can check on things as mentioned above

**Comment by rackifiaustin** [comment]
I am unfortunately getting way too many errors.

`
mktxp@noc:~/mktxp$ mktxp edit
Command 'mktxp' not found, did you mean:
  command 'mktip' from deb kylin-display-switch (3.0.14-1)
Try: apt install <deb name>
`

Then this

`
mktxp@noc:~/mktxp$ docker exec -ti mktxp sh
Error: No such container: mktxp
`

There is no specific tutorial. Now when I log into Prometheus, it shows everything is up but the 49009/metrics comes up as ERR_CONNECTION_REFUSED

**Comment by akpw** [comment]
@rackifiaustin regarding the tutorial, the [readme.md](https://github.com/akpw/mktxp-stack/blob/main/README.md) does provide it?  it basically should be enough to clone/download the repo, fill in your router connection info in `./mktxp/mktxp.conf` file, and then run the docker-compose command as described there

not sure what went wrong, maybe you can just try a fresh install?

**Comment by akpw** [comment]
fyi, I also updated the docker compose files to run mtxp under root. The main reason was addressing [this](https://github.com/akpw/mktxp#mktxp-stack-install), though might be relevant here as well

**Comment by rackifiaustin** [comment]
I am going to try on a clean 22.04 install today :)

**Comment by rackifiaustin** [comment]
> fyi, I also updated the docker compose files to run mtxp under root. The main reason was addressing [this](https://github.com/akpw/mktxp#mktxp-stack-install), though might be relevant here as well

Okay! So I did a clean install on 20.04 - I used my user, selected docker to install upon initial OS install. I then installed Docker Compose vis this with version 2.14.2 - https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-compose-on-ubuntu-20-04

Then, I executed the commands below:

sudo groupadd docker
sudo usermod -aG docker ${USER}
su -s ${USER}
sudo reboot

git clone https://github.com/akpw/mktxp-stack.git
cd mktxp-stack
docker-compose -f ./docker-compose-mktxp-stack.yml up -d

:9090 shows all services are up but on :300- under the "Routerboard" it shows "None". 

I did change the mktxp.conf to Enable : True, changed localhost to my router IP, and put in my API credentials which I double checked.

--UPDATE--
Upon reconfirming the mktxp.conf file and rebooting, now :49090 will not respond and it shows as mktxp is down.

**Comment by akpw** [comment]
OK at that point it likely looks like a mkxp.conf thing
Can you do `docker exec -ti mktxp sh` and then in the containter run `mktxp edit`, to see what what conf file is there? what file path and the content, it the same as what you have in the *mktxp-stack/mktxp/mktxp.conf* on host?

also do you have anything in `docker logs mktxp`?

**Comment by rackifiaustin** [comment]
Okay :)

When executing "docker exec -ti mktxp sh" I received:

`Error response from daemon: Container f2589e3715217864f04c88ab1933345de5b643953c7384921d1d06bb5f20becf is restarting, wait until the container is running
`

But when running "docker log mktxp" I get this errors: https://pastebin.com/vgwX5sAx

--UPDATE--
This is what `.docker ps` shows: https://i.postimg.cc/tTwsWRHK/dockerps.jpg

**Comment by akpw** [comment]
> configobj.ConfigObjError: Parsing failed with several errors.
> First error at line 63

can you check what you have in your mktxp.conf on that line?
likely some formatting mistake in your config file, which is why mktxp can not parse it and so it keeps restarting

**Comment by rackifiaustin** [comment]
Okay! For some reason it had two config's in there - I might've pasted it twice by accident. I am now able to open the mktxp edit within docker, which I need to change the settings as it shows the default localhost.

Standby

**Comment by rackifiaustin** [comment]
Okay - so i edited that docker container mktxp.conf and it generated this format:

`
## Copyright (c) 2020 Arseniy Kuznetsov
##
## This program is free software; you can redistribute it and/or
## modify it under the terms of the GNU General Public License
## as published by the Free Software Foundation; either version 2
## of the License, or (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.


[Core-Router]
    pool = True
    monitor = True
    user = True
    netwatch = True
    use_ssl = False
    poe = True
    public_ip = True
    installed_packages = True
    no_ssl_certificate = False
    enabled = False
    connections = True
    route = True
    queue = True
    firewall = True
    use_comments_over_names = True
    dhcp_lease = True
    interface = True
    wireless = True
    capsman = True
    wireless_clients = True
    ipv6_firewall = False
    dhcp = True
    ssl_certificate_verify = False
    capsman_clients = True
    ipv6_neighbor = False
    hostname = REDACTED
    username = REDACTED
    password = REDACTED
    port = 8728
`
Everything shows up and healthy on Prometheus now but MYIP:49090/metrics is not responding 

--UPDATE--
I confirmed the others, like Loki, metrics are showing but MKTXP isn't. Super odd

**Comment by akpw** [comment]
> enabled = False

this might explain it...

**Comment by rackifiaustin** [comment]
Okay :) 

So I have mktxp working and up and running according to Prometheus, just nothing flowing into Grafana.

It shows "Routerboard: None" on Grafana

There is nothing in logs when I do `docker logs mktxp`

**Comment by akpw** [comment]
`docker exec -ti mktxp sh`, then in the container run `mktxp print -en Core-Router -d`. What do you see?
