### ISSUE TITLE
Ports not configuring???

### ISSUE THREAD

**Issue by crowfeatherjoe** [akpw/mktxp-stack#6]
Im having trouble understanding why the ports didn't get configured for these containers when I use docker-compose?

![image](https://github.com/akpw/mktxp-stack/assets/48198391/9336e6a2-0966-4180-aab8-33c93e12345e)

any ideas?

**Comment by akpw** [comment]
@crowfeatherjoe have not heard about this one before, were you able to figure out what the problem was there?
