### ISSUE TITLE
Multiple routers

### ISSUE THREAD

**Issue by InacomSj** [akpw/mktxp-stack#8]
I can´t set up multiple routers to see them in grafana, only RB4011 its show in the dropbox

this is the config in mktxp.conf
Any help is welcome

`[RB-4011]
    enabled = on         # turns metrics collection for this RouterOS device on / off
    
    hostname = 10.2.1.66    # RouterOS IP address
    port = 8728             # RouterOS IP Port
    
    username = syslog-vm     # RouterOS user, needs to have 'read' and 'api' permissions
    password = xxxxxx
    
    use_ssl = False                 # enables connection via API-SSL servis
    no_ssl_certificate = False      # enables API_SSL connect without router SSL certificate
    ssl_certificate_verify = False  # turns SSL certificate verification on / off   

    installed_packages = True       # Installed packages
    dhcp = True                     # DHCP general metrics
    dhcp_lease = True               # DHCP lease metrics

    connections = True              # IP connections metrics
    connection_stats = False        # Open IP connections metrics 

    pool = True                     # Pool metrics
    interface = True                # Interfaces traffic metrics
    
    firewall = True                 # IPv4 Firewall rules traffic metrics
    ipv6_firewall = False           # IPv6 Firewall rules traffic metrics
    ipv6_neighbor = False           # Reachable IPv6 Neighbors

    poe = True                      # POE metrics
    monitor = True                  # Interface monitor metrics
    netwatch = True                 # Netwatch metrics
    public_ip = True                # Public IP metrics
    route = True                    # Routes metrics
    wireless = True                 # WLAN general metrics
    wireless_clients = True         # WLAN clients metrics
    capsman = True                  # CAPsMAN general metrics
    capsman_clients = True          # CAPsMAN clients metrics    

    user = True                     # Active Users metrics
    queue = True                    # Queues metrics
    
    remote_dhcp_entry = None        # An MKTXP entry for remote DHCP info resolution (capsman/wireless)

    use_comments_over_names = True  # when available, forces using comments over the interfaces names

    check_for_updates = False       # check for available ROS updates
    
[RB-1036]
    enabled = on         # turns metrics collection for this RouterOS device on / off
    
    hostname = 10.1.1.2    # RouterOS IP address
    port = 8728             # RouterOS IP Port
    
    username = syslog-vm     # RouterOS user, needs to have 'read' and 'api' permissions
    password = xxxxxxx
    
    use_ssl = False                 # enables connection via API-SSL servis
    no_ssl_certificate = False      # enables API_SSL connect without router SSL certificate
    ssl_certificate_verify = False  # turns SSL certificate verification on / off   

    installed_packages = True       # Installed packages
    dhcp = True                     # DHCP general metrics
    dhcp_lease = True               # DHCP lease metrics

    connections = True              # IP connections metrics
    connection_stats = False        # Open IP connections metrics 

    pool = True                     # Pool metrics
    interface = True                # Interfaces traffic metrics
    
    firewall = True                 # IPv4 Firewall rules traffic metrics
    ipv6_firewall = False           # IPv6 Firewall rules traffic metrics
    ipv6_neighbor = False           # Reachable IPv6 Neighbors

    poe = True                      # POE metrics
    monitor = True                  # Interface monitor metrics
    netwatch = True                 # Netwatch metrics
    public_ip = True                # Public IP metrics
    route = True                    # Routes metrics
    wireless = True                 # WLAN general metrics
    wireless_clients = True         # WLAN clients metrics
    capsman = True                  # CAPsMAN general metrics
    capsman_clients = True          # CAPsMAN clients metrics    

    user = True                     # Active Users metrics
    queue = True                    # Queues metrics
    
    remote_dhcp_entry = None        # An MKTXP entry for remote DHCP info resolution (capsman/wireless)

    use_comments_over_names = True  # when available, forces using comments over the interfaces names

    check_for_updates = False       # check for available ROS updates

[RB-2004]
    enabled = on         # turns metrics collection for this RouterOS device on / off
    
    hostname = 10.3.254.1    # RouterOS IP address
    port = 8728             # RouterOS IP Port
    
    username = syslog-vm     # RouterOS user, needs to have 'read' and 'api' permissions
    password = xxxxxx
    
    use_ssl = False                 # enables connection via API-SSL servis
    no_ssl_certificate = False      # enables API_SSL connect without router SSL certificate
    ssl_certificate_verify = False  # turns SSL certificate verification on / off   

    installed_packages = True       # Installed packages
    dhcp = True                     # DHCP general metrics
    dhcp_lease = True               # DHCP lease metrics

    connections = True              # IP connections metrics
    connection_stats = False        # Open IP connections metrics 

    pool = True                     # Pool metrics
    interface = True                # Interfaces traffic metrics
    
    firewall = True                 # IPv4 Firewall rules traffic metrics
    ipv6_firewall = False           # IPv6 Firewall rules traffic metrics
    ipv6_neighbor = False           # Reachable IPv6 Neighbors

    poe = True                      # POE metrics
    monitor = True                  # Interface monitor metrics
    netwatch = True                 # Netwatch metrics
    public_ip = True                # Public IP metrics
    route = True                    # Routes metrics
    wireless = True                 # WLAN general metrics
    wireless_clients = True         # WLAN clients metrics
    capsman = True                  # CAPsMAN general metrics
    capsman_clients = True          # CAPsMAN clients metrics    

    user = True                     # Active Users metrics
    queue = True                    # Queues metrics
    
    remote_dhcp_entry = None        # An MKTXP entry for remote DHCP info resolution (capsman/wireless)

    use_comments_over_names = True  # when available, forces using comments over the interfaces names

    check_for_updates = False       # check for available ROS updates
`

**Comment by akpw** [comment]
@InacomSj can you do `docker exec -ti mktxp sh` and see if there are any error messages there?
you can also just try the following config (`enabled = True` instead of `on`), assuming the login infos are correct this should work
```
[RB-4011]
	enabled = True 			# turns metrics collection for this RouterOS device on / off
	
	hostname = 10.2.1.66    # RouterOS IP address
	port = 8728             # RouterOS IP Port
	
	username = syslog-vm    # RouterOS user, needs to have 'read' and 'api' permissions
	password = xxxxxx
	
	use_ssl = False                 # enables connection via API-SSL servis
	no_ssl_certificate = False      # enables API_SSL connect without router SSL certificate
	ssl_certificate_verify = False  # turns SSL certificate verification on / off   
	
	installed_packages = True       # Installed packages
	dhcp = True                     # DHCP general metrics
	dhcp_lease = True               # DHCP lease metrics
	
	connections = True              # IP connections metrics
	connection_stats = False        # Open IP connections metrics 
	
	pool = True                     # Pool metrics
	interface = True                # Interfaces traffic metrics
	
	firewall = True                 # IPv4 Firewall rules traffic metrics
	ipv6_firewall = False           # IPv6 Firewall rules traffic metrics
	ipv6_neighbor = False           # Reachable IPv6 Neighbors
	
	poe = True                      # POE metrics
	monitor = True                  # Interface monitor metrics
	netwatch = True                 # Netwatch metrics
	public_ip = True                # Public IP metrics
	route = True                    # Routes metrics
	wireless = True                 # WLAN general metrics
	wireless_clients = True         # WLAN clients metrics
	capsman = True                  # CAPsMAN general metrics
	capsman_clients = True          # CAPsMAN clients metrics    
	
	user = True                     # Active Users metrics
	queue = True                    # Queues metrics
	
	remote_dhcp_entry = None        # An MKTXP entry for remote DHCP info resolution (capsman/wireless)
	
	use_comments_over_names = True  # when available, forces using comments over the interfaces names
	
	check_for_updates = False       # check for available ROS updates


[RB-1036]
	enabled = True 			# turns metrics collection for this RouterOS device on / off
	
	hostname = 10.1.1.2    	# RouterOS IP address
	port = 8728             # RouterOS IP Port
	
	username = syslog-vm    # RouterOS user, needs to have 'read' and 'api' permissions
	password = xxxxxxx
	
	use_ssl = False                 # enables connection via API-SSL servis
	no_ssl_certificate = False      # enables API_SSL connect without router SSL certificate
	ssl_certificate_verify = False  # turns SSL certificate verification on / off   
	
	installed_packages = True       # Installed packages
	dhcp = True                     # DHCP general metrics
	dhcp_lease = True               # DHCP lease metrics
	
	connections = True              # IP connections metrics
	connection_stats = False        # Open IP connections metrics 
	
	pool = True                     # Pool metrics
	interface = True                # Interfaces traffic metrics
	
	firewall = True                 # IPv4 Firewall rules traffic metrics
	ipv6_firewall = False           # IPv6 Firewall rules traffic metrics
	ipv6_neighbor = False           # Reachable IPv6 Neighbors
	
	poe = True                      # POE metrics
	monitor = True                  # Interface monitor metrics
	netwatch = True                 # Netwatch metrics
	public_ip = True                # Public IP metrics
	route = True                    # Routes metrics
	wireless = True                 # WLAN general metrics
	wireless_clients = True         # WLAN clients metrics
	capsman = True                  # CAPsMAN general metrics
	capsman_clients = True          # CAPsMAN clients metrics    
	
	user = True                     # Active Users metrics
	queue = True                    # Queues metrics
	
	remote_dhcp_entry = None        # An MKTXP entry for remote DHCP info resolution (capsman/wireless)
	
	use_comments_over_names = True  # when available, forces using comments over the interfaces names
	
	check_for_updates = False       # check for available ROS updates

[RB-2004]
	enabled = True 			# turns metrics collection for this RouterOS device on / off
	
	hostname = 10.3.254.1   # RouterOS IP address
	port = 8728             # RouterOS IP Port
	
	username = syslog-vm    # RouterOS user, needs to have 'read' and 'api' permissions
	password = xxxxxx
	
	use_ssl = False                 # enables connection via API-SSL servis
	no_ssl_certificate = False      # enables API_SSL connect without router SSL certificate
	ssl_certificate_verify = False  # turns SSL certificate verification on / off   
	
	installed_packages = True       # Installed packages
	dhcp = True                     # DHCP general metrics
	dhcp_lease = True               # DHCP lease metrics
	
	connections = True              # IP connections metrics
	connection_stats = False        # Open IP connections metrics 
	
	pool = True                     # Pool metrics
	interface = True                # Interfaces traffic metrics
	
	firewall = True                 # IPv4 Firewall rules traffic metrics
	ipv6_firewall = False           # IPv6 Firewall rules traffic metrics
	ipv6_neighbor = False           # Reachable IPv6 Neighbors
	
	poe = True                      # POE metrics
	monitor = True                  # Interface monitor metrics
	netwatch = True                 # Netwatch metrics
	public_ip = True                # Public IP metrics
	route = True                    # Routes metrics
	wireless = True                 # WLAN general metrics
	wireless_clients = True         # WLAN clients metrics
	capsman = True                  # CAPsMAN general metrics
	capsman_clients = True          # CAPsMAN clients metrics    
	
	user = True                     # Active Users metrics
	queue = True                    # Queues metrics
	
	remote_dhcp_entry = None        # An MKTXP entry for remote DHCP info resolution (capsman/wireless)
	
	use_comments_over_names = True  # when available, forces using comments over the interfaces names
	
	check_for_updates = False       # check for available ROS updates
```

**Comment by InacomSj** [comment]
Thank you very much for answering.
After executing the command, I only have the mktxp prompt, without any error
As a curious fact, after entering the grafana ip with the browser, including the name of the node corresponding to each router declared in the configuration (In my case: http://10.1.3.2:3000/?orgId=1&refresh=5m&var -node=RB-1036), began to display in the dropdown box.
OT: i migrated from pfsense, where I had to configure grafana with a setup developed by github user lephisto.
Is there a way to do something similar for mkt? Knowing the bandwidth usage of each service and route used is very useful and would be a great implementation (in my case I have load balancing from multiple ISPs, including caching traffic output through static routes)
Again, thanks so much for your time
