### ISSUE TITLE
Documentation typo

### ISSUE THREAD

**Issue by lacisz491** [akpw/mktxp-stack#9]
Hi Developers!

First of all, I would like to say that you. It's a really great stack!
I just would like to mention a typo here: https://github.com/akpw/mktxp-stack#file-system-based-logs

Current command: 
`docker-compose -f ./docker-compose-mktxp-stack-fs-logs.yml up -d
`
Correct command: 
`docker-compose -f ./docker-compose-mktxp-stack-fs.yml up -d`

There is no - logs.

Thank you all!

**Comment by akpw** [comment]
@lacisz491 thanks for the good words and for the catch, fixed in the docs
